### ISSUE TITLE
Building via gradle causes Jar file to be 1KB

### ISSUE THREAD

**Issue by GaganBhat** [Endoman123/motion-profile-generator#17]
When I do `gradle Jar`, it used to build compile the full program that was independent of the project. 

After switching to the latest commit, doing the same command results in a file that is 1KB that doesn't do anything. 

Here's a screenshot of the file - 
![image](https://user-images.githubusercontent.com/25236969/39898348-ec9f38fe-547b-11e8-8248-f96fa6031839.png)

Running with --stacktrace doesn't give any output.

**Comment by GaganBhat** [comment]
`"C:\Program Files (x86)\Java\jdk1.8.0_151\bin\java" "-javaagent:C:\Program Files\IntelliJ IDEA Community Edition 2017.3.4\lib\idea_rt.jar=54012:C:\Program Files\IntelliJ IDEA Community Edition 2017.3.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\charsets.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\deploy.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\access-bridge-32.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\cldrdata.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\dnsns.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\jaccess.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\jfxrt.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\localedata.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\nashorn.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\sunec.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\sunjce_provider.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\sunmscapi.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\sunpkcs11.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\ext\zipfs.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\javaws.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\jce.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\jfr.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\jfxswt.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\jsse.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\management-agent.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\plugin.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\resources.jar;C:\Program Files (x86)\Java\jdk1.8.0_151\jre\lib\rt.jar;D:\Programming\Java\5190-Motion-Profile-Generator\main-app\out\production\classes;D:\Programming\Java\5190-Motion-Profile-Generator\main-app\out\production\resources;D:\Programming\Java\5190-Motion-Profile-Generator\main-app\lib\Pathfinder-Java-1.8.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\com.opencsv\opencsv\4.1\5d0a1c5f5e94c9fc00a7e6c886e2d2a1511ea95e\opencsv-4.1.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.8.4\d0de1ca9b69e69d1d497ee3c6009d015f64dad57\gson-2.8.4.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\commons-cli\commons-cli\1.4\c51c00206bb913cd8612b24abd9fa98ae89719b1\commons-cli-1.4.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\com.jcraft\jsch\0.1.54\da3584329a263616e277e15462b387addd1b208d\jsch-0.1.54.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.2.41\5e34ca185bbea7452d704ed3537a22314a809383\kotlin-stdlib-jdk8-1.2.41.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-text\1.1\c336bf600f44b88af356c8a85eef4af822b06a4d\commons-text-1.1.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\org.apache.commons\commons-lang3\3.6\9d28a6b23650e8a7e9063c04588ace6cf7012c17\commons-lang3-3.6.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\commons-beanutils\commons-beanutils\1.9.3\c845703de334ddc6b4b3cd26835458cb1cba1f3d\commons-beanutils-1.9.3.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.2.41\d0cfb3ef897c00449e5e696355db9506225fb507\kotlin-stdlib-jdk7-1.2.41.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.2.41\7e34f009642702250bccd9e5255866f408962a05\kotlin-stdlib-1.2.41.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\commons-logging\commons-logging\1.2\4bfc12adfe4842bf07b657f0369c4cb522955686\commons-logging-1.2.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\commons-collections\commons-collections\3.2.2\8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5\commons-collections-3.2.2.jar;C:\Users\Gagan Bhat\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar" com.jtulayan.main.Client
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
	at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:381)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$353(GlassViewEventHandler.java:417)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:416)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
	... 33 more
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\Gagan Bhat\AppData\Local\Temp\nativeutils13644339564655\pathfinderjava.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at jaci.pathfinder.NativeUtils.loadLibraryFromJar(NativeUtils.java:107)
	at jaci.pathfinder.PathfinderJNI.<clinit>(PathfinderJNI.java:13)
	at jaci.pathfinder.Pathfinder.generate(Pathfinder.java:46)
	at com.jtulayan.main.Pathplanner.updateTrajectories(Pathplanner.kt:286)
	at com.jtulayan.ui.javafx.MPGenController.generateTrajectories(MPGenController.java:727)
	at com.jtulayan.ui.javafx.MPGenController.lambda$initialize$11(MPGenController.java:323)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.jtulayan.ui.javafx.MPGenController.addPointOnClick(MPGenController.java:609)
	... 43 more
`

Here's the error I get when I compile it in intelliJ. The application opens, but when I input more than one waypoint, I get this.

**Comment by Endoman123** [comment]
First of all, your runtime error lies in this:
```
java.lang.UnsatisfiedLinkError: C:\Users\Gagan Bhat\AppData\Local\Temp\nativeutils13644339564655\pathfinderjava.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform at java.lang.ClassLoader$NativeLibrary.load(Native Method)
```
I'm going under the assumption that your OS is a 64-bit OS, so you should uninstall all versions of Java and JDK on your computer and install the 64-bit version of both.

As for why your JAR is only 1 KB, can you open up the JAR as an archive and show me the contents via a screenshot?

**Comment by GaganBhat** [comment]
So I reinstalled Java, and it did the trick. I am able to compile and it works well =)

The jar still shows up as 1KB though. Here are the contents of the jar. 

![image](https://user-images.githubusercontent.com/25236969/39970493-ec891e38-56b1-11e8-8ead-25e94fa246fd.png)

Inside the folder is...

![image](https://user-images.githubusercontent.com/25236969/39970494-fabd6e14-56b1-11e8-893b-37a7a8dd42d8.png)

And all that is there within the file is, 

![image](https://user-images.githubusercontent.com/25236969/39970498-121be37e-56b2-11e8-9f7f-6494f07d9015.png)

**Comment by Endoman123** [comment]
Took a lookaround and realized I changed the structure; since I moved the main app into a module called `main-app`, the new command becomes `gradle:main-app:jar:`. This should work.

I should probably override the root's tasks to use the `main-app`'s `run` and `jar` task though.

**Comment by GaganBhat** [comment]
Thanks! It seems to work now =)
